"Database":
  "Type": "Mysql"
  # 数据库地址
  "DbHost": "127.0.0.1"
  # 数据库端口
  "DbPort": "3306"
  # 用户名
  "DbUser": "root"
  # 密码
  "DbPassword": "123456789"
  # 数据库名
  "DbName": "gin-start"
  "MaxIdleConns": 10
  "MaxOpenConns": 100
  "ConnMaxLifetime": 60
  "ConnMaxIdleTime": 1

"Redis":
  "Host": "127.0.0.1"
  "Port": "6379"
  "Password": ""
  "DB": 0

"Self":
  "RouterHost": "0.0.0.0"
  "RouterPort": "8000"

"Distributed":
  "Node": 1

"amap":
  "url": "https://restapi.amap.com/v5/ip?parameters"
  "amap-key": "3481522b7bfcf4dfb43f807f1f7f2f1e"
  "sig": "04668ea835d0c86a4e7f5562c30540f2"

